export const FETCH_USERS_START = 'FETCH_USERS_START'
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE'

export const CHANGE_ACTIVE_USER = 'CHANGE_ACTIVE_USER'
export const SEARCH_USER = 'SEARCH_USER'

export const SORT_USERS = 'SORT_USERS'
export const RESET_FILTERS = 'RESET_FILTERS'